apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: tgis-runtime
spec:
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/text-generation-inference:stable
      command: ["text-generation-launcher"]
      args: 
        - "--model-name=/mnt/models/"
        - "--port=3000"
        - "--grpc-port=8033"
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      # resources: # configure as required
      #   requests:
      #     cpu: 8
      #     memory: 16Gi
      ports:
      - containerPort: 8033
        name: h2c
        protocol: TCP
        