apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: caikit-standalone-runtime
spec:
  multiModel: false
  supportedModelFormats:
    # Note: this currently *only* supports caikit format models
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/caikit-nlp:fast
      command: ["python", "-m", "caikit.runtime"]
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: RUNTIME_GRPC_ENABLED
          value: "false"
        - name: RUNTIME_HTTP_ENABLED
          value: "true"
      ports:
        - containerPort: 8080
          protocol: TCP
      # resources: # configure as required
      #   requests:
      #     cpu: 8
      #     memory: 16Gi
      readinessProbe:
        exec:
          command:
            - python
            - -m
            - caikit_health_probe
            - readiness
        initialDelaySeconds: 5 # might require larger values for large models
      livenessProbe:
        exec:
          command:
            - python
            - -m
            - caikit_health_probe
            - liveness
        initialDelaySeconds: 5
