version: 2

updates:
  - directory: "/"
    package-ecosystem: "poetry"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - directory: "/"
    package-ecosystem: "Docker"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
