apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: caikit-tgis-example-isvc
spec:
  predictor:
    model:
      modelFormat:
        name: caikit
      runtime: caikit-tgis-runtime
      ports:
        - containerPort: 8085
          name: h2c
          protocol: TCP
      storageUri: proto://path/to/model # single model here
      # Example, using a pvc:
      # storageUri: pvc://caikit-pvc/flan-t5-small-caikit/
      # Target directory must contain a config.yml
