apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: caikit-tgis-runtime-grpc
spec:
  multiModel: false
  supportedModelFormats:
    # Note: this currently *only* supports caikit format models
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/text-generation-inference:stable
      command: ["text-generation-launcher"]
      args: ["--model-name=/mnt/models/artifacts/"]
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      # resources: # configure as required
      #   requests:
      #     cpu: 8
      #     memory: 16Gi
    - name: transformer-container
      image: quay.io/opendatahub/caikit-tgis-serving:stable
      command: ["python", "-m", "caikit.runtime.grpc_server"]
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
      ports:
        - containerPort: 8085
          name: h2c
          protocol: TCP
      # resources: # configure as required
      #   requests:
      #     cpu: 8
      #     memory: 16Gi