apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: caikit-tgis-isvc-grpc
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: caikit
      runtime: caikit-tgis-runtime-grpc
      storageUri: s3://modelmesh-example-models/llm/models/flan-t5-small-caikit # single model here
      # storageUri: proto://path/to/model # single model here
      # Example, using a pvc:
      # storageUri: pvc://caikit-pvc/flan-t5-small-caikit/
      # Target directory must contain a config.yml
