apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: caikit-tgis-runtime-grpc
spec:
  multiModel: false
  supportedModelFormats:
    # Note: this currently *only* supports caikit format models
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/text-generation-inference:stable
      ## Note: cannot add readiness/liveness probes to this container because knative will refuse them
      command: ["text-generation-launcher"]
      args: ["--model-name=/mnt/models/artifacts/"]
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      # resources: # configure as required
      #   requests:
      #     cpu: 8
      #     memory: 16Gi
    - name: transformer-container
      image: quay.io/opendatahub/caikit-tgis-serving:stable
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        - name: RUNTIME_GRPC_ENABLED
          value: "true"
        - name: RUNTIME_HTTP_ENABLED
          value: "false"
      ports:
        - containerPort: 8085
          name: h2c
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - python
            - -m
            - caikit_health_probe
            - readiness
      livenessProbe:
        exec:
          command:
            - python
            - -m
            - caikit_health_probe
            - liveness
      # resources: # configure as required
      #   requests:
      #     cpu: 8
      #     memory: 16Gi
