apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: opendatahub
  template: caikit-tgis-serving
metadata:
  annotations:
    description: Caikit is an AI toolkit that enables users to manage models through a set of developer friendly APIs. It provides a consistent format for creating and using AI models against a wide variety of data domains and tasks.
    openshift.io/display-name: Caikit TGIS ServingRuntime for KServe
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: rhods,rhoai,kserve,servingruntime
    template.openshift.io/documentation-url: https://github.com/opendatahub-io/caikit-tgis-serving
    template.openshift.io/long-description: This template defines resources needed to deploy caikit-tgis-serving servingruntime with Red Hat Data Science KServe for LLM model
    template.openshift.io/support-url: https://access.redhat.com
  labels:
    app: opendatahub
  name: caikit-tgis-serving-template
objects:
  - apiVersion: serving.kserve.io/v1alpha1
    kind: ServingRuntime
    metadata:
      name: caikit-tgis-runtime
    spec:
      multiModel: false
      supportedModelFormats:
        # Note: this currently *only* supports caikit format models
        - autoSelect: true
          name: caikit
      containers:
        - name: kserve-container
          image: ${TGIS_CONTAINER_IMAGE}
          command: ["text-generation-launcher"]
          args: ["--model-name=/mnt/models/artifacts/"]
          env:
            - name: TRANSFORMERS_CACHE
              value: /tmp/transformers_cache
          resources: # configure as required
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
        - name: transformer-container
          image: ${CAIKIT_CONTAINER_IMAGE}
          env:
            - name: TRANSFORMERS_CACHE
              value: /tmp/transformers_cache
            - name: RUNTIME_LOCAL_MODELS_DIR
              value: /mnt/models
            - name: TRANSFORMERS_CACHE
              value: /tmp/transformers_cache
            - name: RUNTIME_GRPC_ENABLED
              value: "false"
            - name: RUNTIME_HTTP_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - python
                - -m
                - caikit_health_probe
                - readiness
            initialDelaySeconds: ${PROBES_INITIAL_DELAY_SECONDS}

          livenessProbe:
            exec:
              command:
                - python
                - -m
                - caikit_health_probe
                - liveness
            initialDelaySeconds: ${PROBES_INITIAL_DELAY_SECONDS}

parameters:
  - name: CPU_REQUEST
    description: CPU request for the container
    value: "4"
  - name: MEMORY_REQUEST
    description: Memory request for the container
    value: "8Gi"
  - name: CAIKIT_CONTAINER_IMAGE
    description: Container image for the runtime
    value: quay.io/opendatahub/caikit-tgis-serving:stable
  - name: TGIS_CONTAINER_IMAGE
    description: Container image for the runtime
    value: quay.io/opendatahub/text-generation-inference:stable
  - name: PROBES_INITIAL_DELAY_SECONDS
    description: Time to wait before performing initial probes. Useful when loading large models.
    value: 5
